import { defineConfig } from "vite";
import react from "@vitejs/plugin-react-swc";
import path from "path";
import { componentTagger } from "lovable-tagger";
import prerender from 'vite-plugin-prerender';
import Renderer from '@prerenderer/renderer-puppeteer';
import * as fs from 'fs';

// Load routes for prerendering (generated by scripts/generate-routes.ts)
let routesToPrerender: string[] = [];
try {
  const routesPath = path.resolve(__dirname, 'scripts/routes.json');
  if (fs.existsSync(routesPath)) {
    routesToPrerender = JSON.parse(fs.readFileSync(routesPath, 'utf-8'));
    console.log(`📄 Loaded ${routesToPrerender.length} routes for prerendering`);
  }
} catch (e) {
  console.log('⚠️ No routes.json found, prerendering will be skipped');
}

// https://vitejs.dev/config/
export default defineConfig(({ mode }) => ({
  server: {
    host: "::",
    port: 8080,
  },
  plugins: [
    react(),
    mode === 'development' && componentTagger(),
    mode === 'production' && routesToPrerender.length > 0 && prerender({
      staticDir: path.join(__dirname, 'dist'),
      routes: routesToPrerender,
      renderer: new Renderer({
        renderAfterDocumentEvent: 'prerender-ready',
        headless: true,
        timeout: 60000,
      }),
      postProcess(renderedRoute) {
        // Add prerender indicator for debugging
        renderedRoute.html = renderedRoute.html.replace(
          '</head>',
          '<meta name="prerender-status" content="prerendered" /></head>'
        );
        return renderedRoute;
      },
    }),
  ].filter(Boolean),
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
}));
