import { defineConfig } from "vite";
import react from "@vitejs/plugin-react-swc";
import path from "path";
import { componentTagger } from "lovable-tagger";
import { readFileSync, existsSync } from 'fs';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Load routes for prerendering (generated by scripts/generate-routes.ts)
let routesToPrerender: string[] = [];
try {
  const routesPath = path.resolve(__dirname, 'scripts/routes.json');
  if (existsSync(routesPath)) {
    routesToPrerender = JSON.parse(readFileSync(routesPath, 'utf-8'));
    console.log(`📄 Loaded ${routesToPrerender.length} routes for prerendering`);
  }
} catch (e) {
  console.log('⚠️ No routes.json found, prerendering will be skipped');
}

// https://vitejs.dev/config/
export default defineConfig(({ mode }) => ({
  server: {
    host: "::",
    port: 8080,
  },
  plugins: [
    react(),
    mode === 'development' && componentTagger(),
  ].filter(Boolean),
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
}));
